# Production Environment Configuration
# This file should be configured in Streamlit Cloud or Azure deployment

BACKEND_URL = "http://myapp-prodreadychatbot.eastus.azurecontainer.io:8000"
ENVIRONMENT = "production"
DEBUG = "false"
